import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiSparkles,
  HiLockClosed,
} from "react-icons/hi2";

import { IoLogoTableau } from "react-icons/io5";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiReact,
  SiTypescript,
  SiRedis,
  SiNodedotjs,
  SiPostgresql,
  SiPython,
  SiNumpy,
  SiPandas,
  SiMongodb,
  SiPrisma,
  SiExpress,
  SiTailwindcss,
  SiHtml5,
  SiCss,
  SiGit,
  SiOpenai,
} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, FaAws } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  react: SiReact,
  typescript: SiTypescript,
  redis: SiRedis,
  aws: FaAws,
  nodejs: SiNodedotjs,
  postgresql: SiPostgresql,
  sparkles: HiSparkles,
  lock: HiLockClosed,
  python: SiPython,
  numpy: SiNumpy,
  pandas: SiPandas,
  tableau: IoLogoTableau,
  mongodb: SiMongodb,
  prisma: SiPrisma,
  express: SiExpress,
  tailwindcss: SiTailwindcss,
  html5: SiHtml5,
  css3: SiCss,
  git: SiGit,
  openai: SiOpenai,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
